// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAtXN4NI6jgCEPMJtVypER0hiNkoc14U',
    appId: '1:235397507512:web:b116ce0e81796548eb074d',
    messagingSenderId: '235397507512',
    projectId: 'og9382fxwc1wxc89gfrvv5ovshviyg',
    authDomain: 'og9382fxwc1wxc89gfrvv5ovshviyg.firebaseapp.com',
    storageBucket: 'og9382fxwc1wxc89gfrvv5ovshviyg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjecxVW5hZQk7jNBW4jobwzL45Dz1BQDc',
    appId: '1:235397507512:android:76b7d1a3d09ff195eb074d',
    messagingSenderId: '235397507512',
    projectId: 'og9382fxwc1wxc89gfrvv5ovshviyg',
    storageBucket: 'og9382fxwc1wxc89gfrvv5ovshviyg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQwikbB0TPM3nVuq9hiopAOz3zq-UpUg',
    appId: '1:235397507512:ios:b3057b17acc18f2aeb074d',
    messagingSenderId: '235397507512',
    projectId: 'og9382fxwc1wxc89gfrvv5ovshviyg',
    storageBucket: 'og9382fxwc1wxc89gfrvv5ovshviyg.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
